name: mi second github workflow

on: [label]

jobs:
  main-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code for repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: this should fail
        run: |
          npm ci
          npm test