name: mi first github workflow

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script-stop : false
        script: |
          export PATH="/home/ubuntu/.local/bin:/home/ubuntu/.nvm/versions/node/v15.0.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          cd action
          eval "$(ssh-agent -s)"
          ssh -T git@github.com
          git remote -v
          whoami
          git pull --no-edit origin staging
          npm install
          pm2 delete "action-app"
          pm2 start index.js --name "action-app"