name: mi first github workflow

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd action
          git pull --no-edit origin staging
          npm install
          pm2 delete "action-app" || true
          pm2 start index.js --name "action app"