name: mi first github workflow

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "hello" > file.txt
        name: create file.txt
      - run: cat file.txt
        name: print content of file.txt
      - run: ls
        name: first ls
      - uses: actions/checkout@v2
        name: mi first checkout :D
      - run: ls
        name: second ls